/**
 * Internal Business Error Codes mapping for finer client-side error identification.
 */
const ErrorCodes = {
  // Authentication Errors
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // User Errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

  // Validation & General Request Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  QUEUE_ERROR: 'QUEUE_ERROR',
  WORKER_ERROR: 'WORKER_ERROR',
};

module.exports = ErrorCodes;
